services:
  airflow_db:
    image: postgres:16
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - airflow_db:/var/lib/postgresql/data

  warehouse_db:
    image: postgres:16
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: warehouse
    ports:
      - ":" #write the port you want
    volumes:
      - warehouse_db:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.3
    depends_on:
      airflow_db:
        condition: service_healthy
      warehouse_db:
        condition: service_started
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://POSTGRES_USER:POSTGRES_PASSWORD@airflow_db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Athens
      # Δημιουργεί αυτόματα Airflow connection id: postgres_warehouse
      AIRFLOW_CONN_POSTGRES_WAREHOUSE: postgresql+psycopg2://POSTGRES_USER:POSTGRES_PASSWORD@warehouse_db:5432/warehouse
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -lc "pip install -r /opt/airflow/requirements.txt &&
                airflow db init &&
                airflow users create 
                --username something 
                --password something 
                --firstname something 
                --lastname something 
                --role Admin 
                --email something@something.com &&
                airflow webserver -p 123 & airflow scheduler" 
    ports:
      - ""   #write the port you want

volumes:
  airflow_db:
  warehouse_db:
