services:
  airflow_db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - airflow_db:/var/lib/postgresql/data

  warehouse_db:
    image: postgres:16
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    ports:
      - "5433:5432"
    volumes:
      - warehouse_db:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.3
    depends_on:
      airflow_db:
        condition: service_healthy
      warehouse_db:
        condition: service_started
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Athens
      # Δημιουργεί αυτόματα Airflow connection id: postgres_warehouse
      AIRFLOW_CONN_POSTGRES_WAREHOUSE: postgresql+psycopg2://warehouse:warehouse@warehouse_db:5432/warehouse
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -lc "pip install -r /opt/airflow/requirements.txt &&
                airflow db init &&
                airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com &&
                airflow webserver -p 8080 & airflow scheduler"
    ports:
      - "8080:8080"   # αν θες άλλαξε σε "8090:8080"

volumes:
  airflow_db:
  warehouse_db:
